let labels =[
    'Aaron Judge',          'Aaron Paul',          'Aaron Taylor-Johnson',
    'Abigail Breslin',      'Adam Sandler',        'Adele',
    'Adriana Barraza',      'Adriana Lima',        'Adrianne Palicki',
    'Adrien Brody',         'Akemi Darenogare',    'Al Pacino',
    'Al Roker',             'Alan Alda',           'Alan Arkin',
    'Alan Rickman',         'Albert Brooks',       'Albert Finney',
    'Alec Baldwin',         'Alessandra Ambrosio', 'Alex Pettyfer',
    'Alexander Skarsgard',  'Alexandra Daddario',  'Alexis Thorpe',
    'Ali Larter',           'Alice Eve',           'Alicia Vikander',
    'Alx James',            'Amanda Bynes',        'Amanda Crew',
    'Amanda Peet',          'Amanda Seyfried',     'Amber Heard',
    'Amy Adams',            'Amy Ryan',            'Amy Schumer',
    'Analeigh Tipton',      'Anderson Cooper',     'Andie MacDowell',
    'Andreea Diaconu',      'Andrew Garfield',     'Andrew Lincoln',
    'Andrew Luck',          'Andy Garcia',         'Andy Murray',
    'Andy Samberg',         'Andy Serkis',         'Angela Bassett',
    'Angelina Jolie',       'Anjelica Huston',     'Anna Faris',
    'Anna Friel',           'Anna Kendrick',       'Anna Paquin',
    'Anna Sui',             'AnnaSophia Robb',     'Anne Bancroft',
    'Anne Baxter',          'Anne Hathaway',       'Annette Bening',
    'Anthony Hopkins',      'Anthony Mackie',      'Anthony Perkins',
    'Antonio Banderas',     'Armin Mueller-Stahl', 'Arnold Schwarzenegger',
    'Art Carney',           'Ashley Graham',       'Ashley Greene',
    'Ashley Judd',          'Ashton Kutcher',      'Audrey Hepburn',
    'Audrey Tautou',        'Ava Gardner',         'Barabara Palvin',
    'Barbra Streisand',     'Barry Pepper',        'Bella Hadid',
    'bella thorne',         'Ben Affleck',         'Ben Foster',
    'Ben Johnson',          'Ben Kingsley',        'Ben Stiller',
    'Benedict Cumberbatch', 'Benicio Del Toro',    'Benjamin Bratt',
    'Berenice Bejo',        'Bernie Mac',          'Bette Midler',
    'Betty White',          'Beyonce Knowles',     'Bill Daley',
    'Bill Hader',           'Bill Murray',         'Bill O Reilly',
    'Bill Paxton',          'Bill Pullman',        'Bill Rancic',
    'Billy Bob Thornton'
  ];
  module.exports= labels;